ansible_user: ENC[AES256_GCM,data:ixdWk65i,iv:RwCO0jsv3nX/9GwTaHkiIgYR3LmuScaW8yQeZwX38yY=,tag:MHhKNdzcYNYRQ883ZAzdHw==,type:str]
ansible_become_password: ENC[AES256_GCM,data:qRZzy4pXQ2QH,iv:ITLUWc1GscMuVluLE7ofF9+srbutWrMlS9denr2QeU0=,tag:Da4ENvtG6wvrYEnd1IONDA==,type:str]
ansible_host: ENC[AES256_GCM,data:Gf7XA1q7B0L6vTK/NWk=,iv:U9VwpItEALqPeZ8NQ+k3Kvg9aI7iTv7HpES/XQ79Yc8=,tag:deWBOVt+e+ehmFEFq/jdaQ==,type:str]
ansible_ssh_private_key_file: ENC[AES256_GCM,data:VxDQ0JDiJkut5K7Ha9I=,iv:Xk2yr82YvZKMwGI4CV+FbVsMnYHbzWfMc1qBaYE/zw8=,tag:6gcOFJZsyMurZCSAT/Usrg==,type:str]
ansible_python_interpreter: ENC[AES256_GCM,data:nEHKF3P7SkR3Q0EHuuIWJw==,iv:ayPUs1whGKx2gULS++yW/8hS5f83SCyK+8BEgM2K9to=,tag:xEaiA/VVA/pClfMTnx8ICQ==,type:str]
sops:
    age:
        - recipient: age1dkl6vjdhx22jdwygztkcxkzyss0ajnzfp4k7ryljc0g6egqsuc0s9guqg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VkczOEhXTGxiUXVGUmtW
            TXM2WEliUjVNMTlzU3phL1RNam1yOFVHZFdFCmdiRjZLRW1VM2ErZHVrWXF3YkNK
            SzJDQndrMWZZa1dYeE9waHFTODdsWG8KLS0tIFF4WEZ6Z3FwNDFaKzk4elJVM0J6
            MEtUMzMyU29YK2F3SFhUbG11ZlZvYWMKkvRvCrYpf5l8rc6HNCg1rk3fWmUiJRlR
            pbGWokHmMD0K02IEIjW8icqFRdcfpyRf11ELv0GZm3QkCg7qeOmo7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T14:48:47Z"
    mac: ENC[AES256_GCM,data:oCWaCpVvcT6SS7JqBRVBF1nmInZaaafXNzI9IkkIX0ZLl3LNPXfbjTuU1SpWy7nDr6aUW5WLs0n2Tb1dVe/bwKC2hVkCnXPzf4BfyelpYxS9IokX7F5SjNqZ256RvCDAGgSxWM0TyLB1OrXEuz8joDEAmQbfmotWvs1ZO0XvndU=,iv:50lKzGCxn0s6jwGRh3M7GneYkjUKrK+zI/MC7mnlC7I=,tag:iuv2oJXyhXN0av/T7gm0ZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
