---
arch_gui_apps:
  # Personal
  - ghostty
  - zen-browser-bin
  - opera
  - obsidian
  - ferdium-bin # messengers in one window
  - okular
  - nemo
  - qbittorrent
  - gparted
  - localsend-bin
  # - nekoray-bin
  - ark # unzip
  # Media playing
  - qimgv
  - mpv
  - smplayer
  - libmpeg2
  # Professional
  - anydesk
  - studio-3t
  - dbeaver-ce-bin
  # Sound
  - notify-send
  - paplay
