- name: Home Network
  # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
  # hide-desktop-navigation: true
  columns:
    - size: small
      widgets:
        - $include: plugins/beszel.yml
        - type: dns-stats
          service: adguard
          url: http://adguardhome:80/
          username: administrator
          password: ${ADMIN_PASS}
        - $include: plugins/gatus-full.yml
    - size: full
      widgets:
        - title: Home Network
          type: bookmarks
          groups:
            - title: Public
              hide-arrow: true
              links:
                - title: Blog
                  url: https://blog.${PUBLIC_TOP_DOMAIN}
                  description: Personal blog
                  icon: https://blog.${PUBLIC_TOP_DOMAIN}/favicon.ico
                - title: Frrcode
                  url: https://frrcode.${PUBLIC_TOP_DOMAIN}
                  description: Copany website
                - title: CV
                  url: https://cv.${PUBLIC_TOP_DOMAIN}
                  description: Personal website 
                - title: VPN
                  description: XRay VLESS Server
                  url: http://65.108.86.24:2096/QtgDtgMkbIa2oTPmJT/
                  icon: sh:openvpn
            - title: Local tools
              hide-arrow: true
              links:
                - title: Jellyfin
                  description: Meida server
                  url: http://jellyfin.${LOCAL_MEDIA_DOMAIN}
                  icon: sh:jellyfin
                - title: Sonarr
                  description: TV series management
                  url: http://sonarr.${LOCAL_MEDIA_DOMAIN}
                  icon: sh:sonarr
                - title: Radarr
                  description: Movies management
                  url: http://radarr.${LOCAL_MEDIA_DOMAIN}
                  icon: sh:radarr
                - title: Prowlarr
                  description: Torrent indexer
                  url: http://prowlarr.${LOCAL_MEDIA_DOMAIN}
                  icon: sh:prowlarr
                - title: Bazarr
                  description: Subtitle indexer
                  url: http://bazarr.${LOCAL_MEDIA_DOMAIN}
                  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/bazarr.png
                - title: Miniflux
                  description: Rss platform
                  url: http://rss.${PUBLIC_TOP_DOMAIN}
                  icon: sh:rss-com
                - title: Transmission
                  description: Torrent client
                  url: http://transmission.${LOCAL_MEDIA_DOMAIN}
                  icon: sh:transmission
                - title: Sunshine
                  description: Game streaming
                  url: http://sunshine.${LOCAL_DESKTOP_DOMAIN}
                  icon: sh:sunshine
            - title: Infra Management
              hide-arrow: true
              links:
                - title: AdGuard Home
                  description: Private DNS
                  url: http://dns.${PUBLIC_TOP_DOMAIN}
                  icon: sh:adguard-home
                - title: WG easy
                  url: https://wg-home.${PUBLIC_TOP_DOMAIN}
                  description: Vpn dashboard
                  icon: sh:wireguard
                - title: Portainer
                  url: http://portainer.${TOP_LOCAL_DOMAIN}
                  description: Container management
                  icon: sh:portainer
                - title: Gotify
                  url: https://ntf.${PUBLIC_TOP_DOMAIN}
                  description: Notification server
                  icon: sh:gotify
                - title: Beszel
                  url: http://beszel.${TOP_LOCAL_DOMAIN}
                  description: Systems monitoring
                  icon: sh:beszel
                - title: Gatus
                  url: http://status.${TOP_LOCAL_DOMAIN}
                  description: Health checks
                  icon: sh:gatus
                - title: UpSnap
                  url: http://${LOCAL_DNS}:8090
                  description: Wake on LAN
                  icon: sh:upsnap
                - title: Crowdsec
                  url: http://crowdsec.${TOP_LOCAL_DOMAIN}
                  description: Security Intelligence
                  icon: sh:crowdsec
            - title: Syncthing
              hide-arrow: true
              links:
                - title: Syncthing Edge
                  description: Data sync
                  url: http://sync.${LOCAL_EDGE_DOMAIN}
                  icon: sh:syncthing
                - title: Syncthing Media
                  description: Data sync
                  url: http://sync.${LOCAL_MEDIA_DOMAIN}
                  icon: sh:syncthing
                - title: Syncthing Desktop
                  description: Data sync
                  url: http://sync.${LOCAL_DESKTOP_DOMAIN}
                  icon: sh:syncthing
            - title: Other
              hide-arrow: true
              links:
                - title: Partner Gateway
                  description: Network Gateway
                  url: http://192.168.1.1
                  icon: https://www.partner.co.il/assets/Favicon%2032X32.png
                - title: Comfast Wifi AP
                  description: Wifi Access Point
                  url: http://192.168.1.10
                  icon: https://comfastwifi.com/image/catalog/comfastwifi-ico.png

        - title: Links
          type: bookmarks
          groups:
            - title: Main
              hide-arrow: true
              links:
                - title: Gmail
                  url: https://mail.google.com/mail/
                  icon: sh:gmail
                - title: Docs
                  url: https://drive.google.com/drive/u/0/folders/149gjCP_SOW3ky0dIrIhkLo6zHWru1a5_
                  icon: sh:google-drive
                - title: Calendar
                  url: https://calendar.google.com/
                  icon: sh:google-calendar
                - title: Telegram
                  url: https://web.telegram.org/
                  icon: sh:telegram
            - title: Fun
              hide-arrow: true
              links:
                - title: Youtube
                  url: https://www.youtube.com/
                  icon: sh:youtube
                - title: Music
                  url: https://music.youtube.com/
                  icon: https://music.youtube.com/img/favicon_144.png
                - title: Ororo
                  url: https://ororo.tv/
                  icon: https://ororo.tv/favicon.png
            - title: Local
              hide-arrow: true
              links:
                - title: Localsend
                  url: https://web.localsend.org/
                  icon: sh:localsend
                - title: SMS
                  url: https://messages.google.com/web
                  icon: sh:google-messages
            - title: Git
              color: 10 70 50
              hide-arrow: true
              links:
                - title: dotfiles
                  description: My full dotfiles setup
                  url: https://github.com/petr-nazarov/dotfiles
                  icon: sh:github
                - title: .secrets
                  description: Secrets setup
                  url: https://github.com/petr-nazarov/.secrets
                  icon: sh:github
                - title: infrastructure
                  description: Source of truth for the whole setup
                  url: https://github.com/petr-nazarov/infrastructure
                  icon: sh:github
                - title: zmk-config
                  description: Keyboard configuration
                  url: https://github.com/petr-nazarov/zmk-config
                  icon: sh:github
                - title: blog
                  description: Personal blog
                  url: https://github.com/petr-nazarov/blog
                  icon: sh:github
                - title: vpn
                  description: Vpn setup 
                  url: https://github.com/petr-nazarov/vpn
                  icon: sh:github
            - title: Docs
              hide-arrow: true
              links:
                - title: Glance settings
                  url: https://github.com/glanceapp/glance/blob/main/docs/configuration.md
                  icon: sh:glance
                - title: icons
                  url: https://selfh.st/icons/
                  icon: sh:selfh-st
            - title: Cloud infra
              hide-arrow: true
              links:
                - title: Cloudflare
                  description: DNS register
                  url: https://dash.cloudflare.com/c9e6332b9b4fa2287a90aa55ce22df93/home/domains
                  icon: sh:cloudflare
                - title: Hetzner
                  description: VPS cloud provider
                  url: https://console.hetzner.cloud/projects/2278725/servers
                  icon: sh:hetzner-light
                - title: Aeza
                  description: VPS cloud provider ru
                  url: https://my.aeza.net/home
                  icon: mdi:server-outline
                - title: Umami
                  description: Analitics platform
                  url: https://cloud.umami.is/analytics/eu/websites/
                  icon: sh:umami
                - title: Checkly
                  description: Health check 
                  url: https://app.checklyhq.com/accounts/f1fefea7-5708-4b75-a348-a9839c3feb49
                  icon: https://app.checklyhq.com/static/images/racoon_favicon.png
                - title: UTM.io
                  description: Utm links generator
                  url: https://app.utm.io/team/69c262d8c3bfffd2deef4776/links 
                  icon: https://app.utm.io/a676bd1b63aa6e9a.png
        - type: monitor
          cache: 1m
          title: External
          sites:

# - type: docker-containers
#   cache: 1m
#   title: Uncategorized
