---
enabled_services:
  # Edge
  - caddy
  - adguard
  - ddns
  - certbot
  - wg-easy
  # - crowdsec
  - upsnap
  - portainer
  - gotify
  - glance
  - gatus
  - beszel
  - rss
  # - cv
  ## Media
  - jellyfin
  - sonarr
  - radarr
  - prowlarr
  - bazarr
  - transmission
  # Multihost
  - backup
  - syncthing
